package br.com.planesdata.mtg.rest.cards.dto.response;

import br.com.planesdata.mtg.models.Card;
import br.com.planesdata.mtg.rest.cards.dto.AllPartDTO;
import br.com.planesdata.mtg.rest.cards.dto.CardFaceDTO;
import br.com.planesdata.mtg.rest.cards.dto.ImageUriDTO;
import br.com.planesdata.mtg.rest.cards.dto.LegalityDTO;
import br.com.planesdata.mtg.rest.cards.dto.PreviewDTO;
import br.com.planesdata.mtg.rest.cards.dto.PriceDTO;
import br.com.planesdata.mtg.rest.cards.dto.PurchaseUriDTO;
import br.com.planesdata.mtg.rest.cards.dto.RelatedUriDTO;
import com.fasterxml.jackson.annotation.JsonInclude;

import java.util.List;
import java.util.Objects;

import static com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL;

@JsonInclude(NON_NULL)
public record CardResponseDTO(String type,
                              String id,
                              String oracleID,
                              List<Integer> multiverseIDs,
                              Integer mtgoID,
                              Integer arenaId,
                              Integer mtgoFoilID,
                              Integer tcgPlayerID,
                              Integer cardMarketID,
                              String name,
                              String lang,
                              String releasedAt,
                              String uri,
                              String scryfallURI,
                              String layout,
                              String highresImage,
                              String imageStatus,
                              ImageUriDTO imageURI,
                              String manaCost,
                              String cmc,
                              String typeLine,
                              String oracleText,
                              String power,
                              String toughness,
                              List<String> colors,
                              List<String> colorIndicators,
                              List<String> keywords,
                              List<CardFaceDTO> cardFaces,
                              List<AllPartDTO> allParts,
                              List<String> producedMana,
                              LegalityDTO legality,
                              List<String> games,
                              Boolean reserved,
                              Boolean gameChanger,
                              Boolean foil,
                              Boolean nonFoil,
                              List<String> finishes,
                              Boolean oversized,
                              Boolean promo,
                              Boolean reprint,
                              String printedName,
                              String printedText,
                              String printedTypeLine,
                              List<String> promoTypes,
                              String loyalty,
                              String lifeModifier,
                              String handModifier,
                              List<String> attractionLights,
                              Boolean variation,
                              String variationOf,
                              String setID,
                              String set,
                              String setName,
                              String setType,
                              String setUri,
                              String setSearchUri,
                              String scryfallUri,
                              String rulingsUri,
                              String printsSearchUri,
                              String collectorNumber,
                              Boolean digital,
                              String rarity,
                              String flavorText,
                              String cardbackId,
                              String artist,
                              List<String> artistIDs,
                              String illustrationID,
                              String borderColor,
                              String frame,
                              String defense,
                              Integer tcgplayerEtchedID,
                              List<String> frameEffects,
                              String flavorName,
                              String contentWarning,
                              String securityStamp,
                              Boolean fullArt,
                              Boolean textless,
                              Boolean booster,
                              String storySpotlight,
                              Integer edhrecRank,
                              PreviewDTO preview,
                              String watermark,
                              Integer pennyRank,
                              PriceDTO price,
                              RelatedUriDTO relatedUri,
                              PurchaseUriDTO purchaseUri) {

    public static CardResponseDTO toDto(Card model) {
        ImageUriDTO imageUri = Objects.nonNull(model.getImageURI()) ? ImageUriDTO.toDto(model.getImageURI()) : null;
        List<CardFaceDTO> cardFaces = Objects.nonNull(model.getCardFaces()) ? model.getCardFaces().stream().map(CardFaceDTO::toDto).toList() : null;
        List<AllPartDTO> allParts = Objects.nonNull(model.getAllParts()) ? model.getAllParts().stream().map(AllPartDTO::toDto).toList() : null;
        LegalityDTO legality = Objects.nonNull(model.getLegality()) ? LegalityDTO.toDto(model.getLegality()) : null;
        PreviewDTO preview = Objects.nonNull(model.getPreview()) ? PreviewDTO.toDto(model.getPreview()) : null;
        PriceDTO price = Objects.nonNull(model.getPrice()) ? PriceDTO.toDto(model.getPrice()) : null;
        RelatedUriDTO related = Objects.nonNull(model.getRelatedUri()) ? RelatedUriDTO.toDto(model.getRelatedUri()) : null;
        PurchaseUriDTO purchase = Objects.nonNull(model.getPurchaseUri()) ? PurchaseUriDTO.toDto(model.getPurchaseUri()) : null;

        return new CardResponseDTO(
                        model.getType(),
                        model.getId(),
                        model.getOracleID(),
                        model.getMultiverseIDs(),
                        model.getMtgoID(),
                        model.getArenaId(),
                        model.getMtgoFoilID(),
                        model.getTcgPlayerID(),
                        model.getCardMarketID(),
                        model.getName(),
                        model.getLang(),
                        model.getReleasedAt(),
                        model.getUri(),
                        model.getScryfallURI(),
                        model.getLayout(),
                        model.getHighresImage(),
                        model.getImageStatus(),
                        imageUri,
                        model.getManaCost(),
                        model.getCmc(),
                        model.getTypeLine(),
                        model.getOracleText(),
                        model.getPower(),
                        model.getToughness(),
                        model.getColors(),
                        model.getColorIndicators(),
                        model.getKeywords(),
                        cardFaces,
                        allParts,
                        model.getProducedMana(),
                        legality,
                        model.getGames(),
                        model.getReserved(),
                        model.getGameChanger(),
                        model.getFoil(),
                        model.getNonFoil(),
                        model.getFinishes(),
                        model.getOversized(),
                        model.getPromo(),
                        model.getReprint(),
                        model.getPrintedName(),
                        model.getPrintedText(),
                        model.getPrintedTypeLine(),
                        model.getPromoTypes(),
                        model.getLoyalty(),
                        model.getLifeModifier(),
                        model.getHandModifier(),
                        model.getAttractionLights(),
                        model.getVariation(),
                        model.getVariationOf(),
                        model.getSetID(),
                        model.getSet(),
                        model.getSetName(),
                        model.getSetType(),
                        model.getSetUri(),
                        model.getSetSearchUri(),
                        model.getScryfallURI(),
                        model.getRulingsUri(),
                        model.getPrintsSearchUri(),
                        model.getCollectorNumber(),
                        model.getDigital(),
                        model.getRarity(),
                        model.getFlavorText(),
                        model.getCardbackId(),
                        model.getArtist(),
                        model.getArtistIDs(),
                        model.getIllustrationID(),
                        model.getBorderColor(),
                        model.getFrame(),
                        model.getDefense(),
                        model.getTcgplayerEtchedID(),
                        model.getFrameEffects(),
                        model.getFlavorName(),
                        model.getContentWarning(),
                        model.getSecurityStamp(),
                        model.getFullArt(),
                        model.getTextless(),
                        model.getBooster(),
                        model.getStorySpotlight(),
                        model.getEdhrecRank(),
                        preview,
                        model.getWatermark(),
                        model.getPennyRank(),
                        price,
                        related,
                        purchase);
    }
}