package br.com.planesdata.mtg.rest.cards.dto.response;

import br.com.planesdata.mtg.models.Card;
import br.com.planesdata.mtg.rest.cards.dto.AllPartDTO;
import br.com.planesdata.mtg.rest.cards.dto.CardFaceDTO;
import br.com.planesdata.mtg.rest.cards.dto.ImageUriDTO;
import br.com.planesdata.mtg.rest.cards.dto.LegalityDTO;
import com.fasterxml.jackson.annotation.JsonInclude;

import java.util.List;
import java.util.Objects;

import static com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL;

// @JsonInclude(NON_NULL)
public record CardResponseDTO(String type,
                              String id,
                              String oracleID,
                              List<Integer> multiverseIDs,
                              String name,
                              String lang,
                              String releasedAt,
                              String layout,
                              String highresImage,
                              String imageStatus,
                              ImageUriDTO imageURI,
                              String manaCost,
                              String cmc,
                              String typeLine,
                              String oracleText,
                              String power,
                              String toughness,
                              List<String> colors,
                              List<String> colorIndicators,
                              List<String> colorIdentities,
                              List<String> keywords,
                              List<CardFaceDTO> cardFaces,
                              List<AllPartDTO> allParts,
                              List<String> producedMana,
                              LegalityDTO legality,
                              List<String> games,
                              Boolean reserved,
                              Boolean gameChanger,
                              Boolean foil,
                              Boolean nonFoil,
                              List<String> finishes,
                              Boolean oversized,
                              Boolean promo,
                              Boolean reprint,
                              String printedName,
                              String printedText,
                              String printedTypeLine,
                              List<String> promoTypes,
                              String loyalty,
                              String lifeModifier,
                              String handModifier,
                              List<String> attractionLights,
                              Boolean variation,
                              String variationOf,
                              String setID,
                              String set,
                              String setName,
                              String setType,
                              String collectorNumber,
                              String rarity,
                              String flavorText,
                              String cardbackId,
                              String artist,
                              List<String> artistIDs,
                              String illustrationID,
                              String borderColor,
                              String frame,
                              String defense) {

    public static CardResponseDTO toDto(Card model) {
        ImageUriDTO imageUri = Objects.nonNull(model.getImageURI()) ? ImageUriDTO.toDto(model.getImageURI()) : null;
        List<CardFaceDTO> cardFaces = Objects.nonNull(model.getCardFaces()) ? model.getCardFaces().stream().map(CardFaceDTO::toDto).toList() : null;
        List<AllPartDTO> allParts = Objects.nonNull(model.getAllParts()) ? model.getAllParts().stream().map(AllPartDTO::toDto).toList() : null;
        LegalityDTO legality = Objects.nonNull(model.getLegality()) ? LegalityDTO.toDto(model.getLegality()) : null;

        return new CardResponseDTO(
                        model.getType(),
                        model.getId(),
                        model.getOracleID(),
                        model.getMultiverseIDs(),
                        model.getName(),
                        model.getLang(),
                        model.getReleasedAt(),
                        model.getLayout(),
                        model.getHighresImage(),
                        model.getImageStatus(),
                        imageUri,
                        model.getManaCost(),
                        model.getCmc(),
                        model.getTypeLine(),
                        model.getOracleText(),
                        model.getPower(),
                        model.getToughness(),
                        model.getColors(),
                        model.getColorIndicators(),
                        model.getColorIdentities(),
                        model.getKeywords(),
                        cardFaces,
                        allParts,
                        model.getProducedMana(),
                        legality,
                        model.getGames(),
                        model.getReserved(),
                        model.getGameChanger(),
                        model.getFoil(),
                        model.getNonFoil(),
                        model.getFinishes(),
                        model.getOversized(),
                        model.getPromo(),
                        model.getReprint(),
                        model.getPrintedName(),
                        model.getPrintedText(),
                        model.getPrintedTypeLine(),
                        model.getPromoTypes(),
                        model.getLoyalty(),
                        model.getLifeModifier(),
                        model.getHandModifier(),
                        model.getAttractionLights(),
                        model.getVariation(),
                        model.getVariationOf(),
                        model.getSetID(),
                        model.getSet(),
                        model.getSetName(),
                        model.getSetType(),
                        model.getCollectorNumber(),
                        model.getRarity(),
                        model.getFlavorText(),
                        model.getCardbackId(),
                        model.getArtist(),
                        model.getArtistIDs(),
                        model.getIllustrationID(),
                        model.getBorderColor(),
                        model.getFrame(),
                        model.getDefense());
    }
}